import { TrainingClass } from './types';

export const trainingClassesData: TrainingClass[] = [
  // II. CÁC LỚP BỒI DƯỠNG (Chuyển tiếp)
  {
    id: 'BD-01',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng cán bộ Văn phòng Đảng ủy cấp xã',
    targetAudience: 'Chánh văn phòng, Phó Chánh văn phòng Đảng ủy',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T5/2026 - T6/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-02',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng cán bộ Ban xây dựng Đảng cấp xã',
    targetAudience: 'Trưởng ban, Phó Trưởng ban Xây dựng Đảng cấp xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T3/2026 - T8/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'In Progress'
  },
  {
    id: 'BD-03',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng cán bộ Ủy Ban kiểm tra Đảng ủy cấp xã',
    targetAudience: 'Chủ nhiệm, Phó Chủ nhiệm UBKT',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T5/2026 - T6/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-04',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng cán bộ Trung tâm Chính trị cấp xã',
    targetAudience: 'Giám đốc, Phó Giám đốc TTCT cấp xã',
    numClasses: 2,
    numStudents: 44,
    mode: 'Không tập trung',
    timeframe: 'T5/2026 - T6/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-05',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng ứng dụng CNTT tại cơ sở',
    targetAudience: 'Công chức Phòng Kinh tế, Văn hóa - Xã hội',
    numClasses: 2,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T5/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-06',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng số và chuyển đổi số cho công chức cấp xã',
    targetAudience: 'Công chức Văn phòng, HĐND, UBND cấp xã',
    numClasses: 9,
    numStudents: 885,
    mode: 'Không tập trung',
    timeframe: 'T4/2026 - T6/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-07',
    category: 'Bồi dưỡng',
    title: 'Đạo đức, văn hoá công vụ cho công chức cấp xã',
    targetAudience: 'Công chức Văn phòng, HĐND, UBND cấp xã',
    numClasses: 8,
    numStudents: 885,
    mode: 'Không tập trung',
    timeframe: 'T3/2026 - T5/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'In Progress'
  },
  {
    id: 'BD-08',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng ngạch chuyên viên chính',
    targetAudience: 'Công chức theo QĐ 421/QĐ-BNV',
    numClasses: 3,
    numStudents: 156,
    mode: 'Không tập trung',
    timeframe: 'T11/2025 - T6/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'In Progress'
  },
  {
    id: 'BD-09',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng ngạch chuyên viên',
    targetAudience: 'Công chức theo QĐ 420/QĐ-BNV',
    numClasses: 2,
    numStudents: 96,
    mode: 'Tập trung',
    timeframe: 'Năm 2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-10',
    category: 'Bồi dưỡng',
    title: 'Quản lý hành chính, kinh tế - xã hội chuyên sâu (CBCC xã)',
    targetAudience: 'Cán bộ, công chức xã',
    numClasses: 2,
    numStudents: 115,
    mode: 'Tập trung',
    timeframe: 'T5/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-11',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo, quản lý cấp xã (Chủ tịch, Phó CT)',
    targetAudience: 'Chủ tịch, Phó Chủ tịch UBND cấp xã',
    numClasses: 1,
    numStudents: 56,
    mode: 'Không tập trung',
    timeframe: 'Quý III/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },

  // II. CÁC LỚP BỒI DƯỠNG (Mở mới 2026)
  {
    id: 'BD-12',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo cho VP HĐND và UBND cấp xã',
    targetAudience: 'Chánh văn phòng, Phó Chánh văn phòng HĐND, UBND xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T8/2026 - T11/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-13',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo cho Phòng Văn hóa - Xã hội cấp xã',
    targetAudience: 'Trưởng phòng, Phó Trưởng phòng VH-XH xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T8/2026 - T10/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-14',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo cho Phòng Kinh tế/Hạ tầng/Đô thị cấp xã',
    targetAudience: 'Trưởng phòng, Phó Trưởng phòng Kinh tế/Hạ tầng/Đô thị xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T8/2026 - T9/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-15',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo Trung tâm Phục vụ hành chính công cấp xã',
    targetAudience: 'Phó Giám đốc Trung tâm PV HCC cấp xã',
    numClasses: 2,
    numStudents: 95,
    mode: 'Không tập trung',
    timeframe: 'T8/2026 - T10/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-16',
    category: 'Bồi dưỡng',
    title: 'Kỹ năng lãnh đạo Ban chỉ huy quân sự cấp xã',
    targetAudience: 'Chỉ huy trưởng, Phó Chỉ huy trưởng BCH Quân sự xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T8/2026 - T9/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-17',
    category: 'Bồi dưỡng',
    title: 'Cập nhật kiến thức cho cấp ủy cấp xã nhiệm kỳ 2025-2030',
    targetAudience: 'Đảng ủy viên cấp xã',
    numClasses: 10,
    numStudents: 475,
    mode: 'Không tập trung',
    timeframe: 'T10/2026 - T12/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-18',
    category: 'Bồi dưỡng',
    title: 'Bồi dưỡng chuyên môn Hội nông dân cấp xã',
    targetAudience: 'Chủ tịch, Phó Chủ tịch Hội nông dân xã',
    numClasses: 4,
    numStudents: 190,
    mode: 'Không tập trung',
    timeframe: 'T10/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-19',
    category: 'Bồi dưỡng',
    title: 'Đổi mới sáng tạo & CĐS (Trung tâm PV HCC)',
    targetAudience: 'Lãnh đạo, công chức Trung tâm PV HCC xã',
    numClasses: 4,
    numStudents: 200,
    mode: 'Không tập trung',
    timeframe: 'T10/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-20',
    category: 'Bồi dưỡng',
    title: 'Khoa học công nghệ & Kỹ năng số cho công chức xã',
    targetAudience: 'Cán bộ, công chức xã, bộ phận Một cửa',
    numClasses: 4,
    numStudents: 160,
    mode: 'Không tập trung',
    timeframe: 'T10/2026 - T11/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-21',
    category: 'Bồi dưỡng',
    title: 'Đại biểu Hội đồng nhân dân cấp xã',
    targetAudience: 'Đại biểu HĐND cấp xã nhiệm kỳ 2026-2031',
    numClasses: 50,
    numStudents: 5000,
    mode: 'Không tập trung',
    timeframe: 'Quý III/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  },
  {
    id: 'BD-22',
    category: 'Bồi dưỡng',
    title: 'Vị trí việc làm lãnh đạo cấp phòng ở cấp xã',
    targetAudience: 'Lãnh đạo, quản lý cấp phòng ở cấp xã',
    numClasses: 13,
    numStudents: 662,
    mode: 'Không tập trung',
    timeframe: 'Quý III/2026',
    location: 'Trường Chính trị tỉnh',
    funding: 'Ngân sách tỉnh',
    status: 'Planned'
  }
];
